language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "python -m pip install -U pip"
  - "pip install --upgrade setuptools"
  - "pip install -r requirements.txt"

script:
  - nosetests -v -s --logging-clear-handlers --with-doctest
