schema_version:
    type: string
    default: 0.1.0
_id:
    type: objectid
    default_setter: objectid
_type:
    type: string
    default: project
created_at:
    type: datetime
    default_setter: utcnow
created_by:
    type: string
    default_setter: getuser
name:
    type: string
    required: True
description:
    type: string
    default_setter: empty_string
thumbnail:
    type: binary
locations:
    type: dict
    valueschema:
        type: string
    required: True
tree:
    type: dict
    allow_unknown: True
    valueschema:
        type: string
    schema:
        folders:
            type: string
        asset:
            type: string
        asset_work:
            type: string
        asset_publish:
            type: string
        asset_review:
            type: string
        file:
            type: string
        sequence:
            type: string
    default:
        folders: ''
        asset: '{asset}'
        asset_work: '{asset}/{task}/work/{host}'
        asset_publish: '{asset}/{task}/publish/{host}'
        asset_review: '{asset}/review'
        file: '{name}_{task}_v{version:0>3d}.{ext}'
        instance_file: '{name}_{task}_{instance:0>2d}_v{version:0>3d}.{ext}'
        sequence: '{task}_{name}_v{version:0>3d}.{frame:0>4d}.{ext}'
