schema_version:
    type: string
    default: 0.1.0

_id:
    type: objectid
    default_setter: objectid

_type:
    type: string
    default: project

name:
    type: string
    required: True

description:
    type: string
    default_setter: empty_string

created_at:
    type: datetime
    default_setter: utcnow

created_by:
    type: string
    default_setter: getuser

fps:
    type: float
    default: 24.0

people:
    type: dict
    allow_unknown: True
    valuesrules:
        type: string
    required: False

tree:
    type: dict
    allow_unknown: True
    valuesrules:
        type: string
    schema:
        bin:
            type: string
        asset:
            type: string
        workspace:
            type: string
        publish:
            type: string
        review:
            type: string
        render:
            type: string
        file:
            type: string
        file_sequence:
            type: string
    default:
        asset: '{mount}/{project}/{bin}/{asset}'
        workspace: '{mount}/{project}/{bin}/{asset}/work/{task}/{host}'
        publish: '{mount}/{project}/{bin}/{asset}/publish/{task_short}_{name}/v{version:0>3d}'
        review: '{mount}/{project}/{bin}/{asset}/review/{task}/{host}'
        render: '{mount}/{project}/{bin}/{asset}/render/{task}/{host}'
        file: '{task_short}_{name}_v{version:0>3d}.{ext}'
        file_sequence: '{task_short}_{name}_v{version:0>3d}.{frame}.{ext}'

asset_types:
    type: dict
    allow_unknown: True
    valuesrules:
        type: dict
        require_all: True
        schema:
            name:
                type: string
            icon:
                type: string
                default: empty_string
            order:
                type: integer
    default:
        asset:
            name: asset
            icon: asset.svg
            order: 0
        shot:
            name: shot
            icon: shot.svg
            order: 1

task_types:
    type: dict
    allow_unknown: True
    valuesrules:
        type: dict
        require_all: True
        schema:
            name:
                type: string
            short:
                type: string
            icon:
                type: string
                default: empty_string
            order:
                type: integer
    default:
        design:
            name: design
            short: dsn
            icon: design.svg
            order: 0
        model:
            name: model
            short: mdl
            icon: model.svg
            order: 1
        texture:
            name: texture
            short: tx
            icon: texture.svg
            order: 2
        shade:
            name: shade
            short: shd
            icon: shade.svg
            order: 3
        rig:
            name: rig
            short: rig
            icon: rig.svg
            order: 4
        animation:
            name: animation
            short: anim
            icon: anim.svg
            order: 5
        fx:
            name: fx
            short: fx
            icon: fx.svg
            order: 6
        lighting:
            name: lighting
            short: lgt
            icon: light.svg
            order: 7
        compositing:
            name: compositing
            short: comp
            icon: comp.svg
            order: 8

bins:
    type: dict
    allow_unknown: True
    valuesrules:
        type: dict
        require_all: True
        schema:
            name:
                type: string
            icon:
                type: string
                default_setter: empty_string
            order:
                type: integer
    default:
        assets:
            name: assets
            icon: asset.svg
            order: 0
        shots:
            name: shots
            icon: shot.svg
            order: 1

assets:
    type: dict
    allow_unknown: True
    valuesrules:
        type: dict
        require_all: True
        schema:
            _id:
                type: objectid
            name:
                type: string
            bin:
                type: string
            asset_type:
                type: string
            group:
                type: string
                default_setter: empty_string
