

WAITING = 'WAITING'
PENDING = 'PENDING'
RUNNING = 'RUNNING'
SUCCESS = 'SUCCESS'
FAILED = 'FAILED'
SKIPPED = 'SKIPPED'
PAUSED = 'PAUSED'
DISABLED = 'DISABLED'
ENABLED = 'ENABLED'
DONE_STATUSES = [SUCCESS, FAILED]
